[package]
name = "aggregator"
version = "0.1.0"
edition = "2018"
rust = "1.31.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.14.3", default-features = false, features = ["raw"] }
